spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nordicjobagent
    username: admin
    password: admin
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen3:8b
      embedding:
        model: mxbai-embed-large
    vectorstore:
      pgvector:
        initialize-schema: true

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true